"""
===========================================================
AIOS Registry Writer
core/keywords/registry_writer.py
===========================================================

Writes keyword registries back to disk.

Responsibilities
----------------
• Serialize registry dictionaries
• Save registry safely
• Keep deterministic formatting

Future
------
• Backup registry versions
• Git snapshots
• Atomic writes
• Rollback
• Pretty formatting

Version
1.0
===========================================================
"""

from pathlib import Path
from pprint import pformat


class RegistryWriter:

    def __init__(self):

        self.generated_folder = Path(
            "core/keywords/generated"
        )

        self.generated_folder.mkdir(
            parents=True,
            exist_ok=True
        )

    # --------------------------------------------------
    # Save registry
    # --------------------------------------------------

    def save(self, domain, registry):

        filename = self.generated_folder / f"{domain}.py"

        variable = domain.upper()

        text = f'''"""
===========================================================
AUTO-GENERATED BY AIOS

Domain : {domain}

DO NOT EDIT MANUALLY

===========================================================
"""

{variable} = {pformat(registry, sort_dicts=False)}
'''

        filename.write_text(
            text,
            encoding="utf-8"
        )

        return filename